Repository qoollo/bob, pull requests merged in 2022-07, with the labels that each got.

#442 Authorization logic bobp
  CHANGELOG.md
  bob-apps/bin/bobp.rs
Labels: required for release

#217 Access management
  .vscode/settings.json
  CHANGELOG.md
  Cargo.toml
  bob-access/Cargo.toml
  bob-access/src/authenticator/basic.rs
  bob-access/src/authenticator/mod.rs
  bob-access/src/authenticator/stub.rs
  bob-access/src/authenticator/users_storage/config.rs
  bob-access/src/authenticator/users_storage/hash_map.rs
  bob-access/src/authenticator/users_storage/mod.rs
  bob-access/src/credentials.rs
  bob-access/src/error.rs
  bob-access/src/extractor.rs
  bob-access/src/lib.rs
  bob-access/src/permissions.rs
  bob-access/src/settings.rs
  bob-access/src/token.rs
  bob-apps/Cargo.toml
  bob-apps/bin/bobc.rs
  bob-apps/bin/bobd.rs
  bob-apps/bin/bobp.rs
  bob-backend/build.rs
  bob-backend/src/core.rs
  bob-backend/src/pearl/core.rs
  bob-backend/src/pearl/group.rs
  bob-backend/src/pearl/tests.rs
  bob-backend/src/pearl/utils.rs
  bob-common/Cargo.toml
  bob-common/build.rs
  bob-common/src/bob_client.rs
  bob-common/src/configs/cluster.rs
  bob-common/src/configs/cluster_tests.rs
  bob-common/src/configs/node.rs
  bob-common/src/data.rs
  bob-common/src/metrics/collector/snapshot.rs
  bob-common/src/metrics/exporters/global_exporter/mod.rs
  bob-common/src/node.rs
  bob/Cargo.toml
  bob/src/api/http.rs
  bob/src/api/http/s3.rs
  bob/src/api/metric_models.rs
  bob/src/api/mod.rs
  bob/src/api/s3.rs
  bob/src/build_info/mod.rs
  bob/src/lib.rs
  bob/src/link_manager.rs
  bob/src/server.rs
  config-examples/node.yaml
  config-examples/openapi.yaml
  config-examples/users.yaml
  dockerfiles/alpine/Dockerfile
  dockerfiles/default-configs/node.yaml
  dockerfiles/default-configs/users.yaml
  dockerfiles/ubuntu/Dockerfile
  test_env/node1.yaml
Labels: feature, required for release

#427 Logstash support
  CHANGELOG.md
  bob-apps/Cargo.toml
  bob-apps/bin/bobd.rs
  config-examples/logger.yaml
Labels: required for release

#523 Bob logo
  README.md
  logo/bob-git-docker-logo.svg
  logo/brandmark.svg
  logo/horizontal.svg
  logo/vertical.svg
Labels: Skip-Changelog

#541 528 correct auth error bobp
  CHANGELOG.md
  bob-access/src/error.rs
Labels: required for release

#535 408 user auth claims
  CHANGELOG.md
  bob-access/src/authenticator/users_storage/config.rs
  config-examples/users.yaml
Labels: required for release

#536 304 password hash ability
  CHANGELOG.md
  bob-access/Cargo.toml
  bob-access/src/authenticator/basic.rs
  bob-access/src/authenticator/stub.rs
  bob-access/src/authenticator/users_storage/config.rs
  bob-access/src/authenticator/users_storage/hash_map.rs
  bob-access/src/authenticator/users_storage/mod.rs
  bob-access/src/lib.rs
  bob-apps/bin/bobd.rs
  config-examples/users.yaml
Labels: required for release

#543 437 support default user
  CHANGELOG.md
  bob-access/src/authenticator/users_storage/config.rs
  bob-access/src/extractor.rs
  config-examples/users.yaml
Labels: required for release

#542 Bobt
  CHANGELOG.md
  bob-apps/Cargo.toml
  bob-apps/bin/bobt.rs
  dockerfiles/alpine/Dockerfile
  dockerfiles/ubuntu/Dockerfile
Labels: required for release
