Repository qoollo/bob, pull requests merged in 2022-01, with the labels that each got.

#412 Change ubuntu 20.10 to 20.04
  .github/workflows/build-docker-images.yml
  CHANGELOG.md
  dockerfiles/ubuntu/Dockerfile
Labels: backport to v2.0

#387 359 use of lsof
  CHANGELOG.md
  bob/Cargo.toml
  bob/src/hw_metrics_collector.rs
Labels: required for release

#392 388 human readable formats
  CHANGELOG.md
  bob-common/Cargo.toml
  bob-common/src/configs/node.rs
  config-examples/node.yaml
Labels: required for release

#390 389 mockclient panic
  .github/workflows/tests.yml
  CHANGELOG.md
  Makefile
  bob-backend/Cargo.toml
  bob-common/Cargo.toml
  bob-common/src/bob_client.rs
  bob/Cargo.toml
  bob/src/cluster/tests.rs
Labels: required for release, backport to v2.0

#423 405 deletion fix backport to 2.0.0
  CHANGELOG.md
  bob/src/api/http.rs
Labels: required for release

#406 405-deletion-fix
  CHANGELOG.md
  bob/src/api/http.rs
Labels: required for release, backport to v2.0
