Repository qoollo/bob, pull requests merged in 2022-04, with the labels that each got.

#399 342 more disk metrics
  CHANGELOG.md
  bob-common/src/metrics/mod.rs
  bob/src/hw_metrics_collector.rs
Labels: required for release

#451 438 send memory fix
  CHANGELOG.md
  bob-common/src/bob_client.rs
  bob-common/src/node.rs
Labels: required for release, backport to v2.0

#418 370 remove dcr
  CHANGELOG.md
  bob-apps/bin/dcr.rs
  bob-apps/bin/docker_cluster_runner/docker_compose_wrapper.rs
  bob-apps/bin/docker_cluster_runner/filesystem_constants.rs
  bob-apps/bin/docker_cluster_runner/logger.rs
  bob-apps/bin/docker_cluster_runner/mod.rs
  bob-apps/bin/docker_cluster_runner/ssh_generation.rs
Labels: required for release

#439 Hierarchical range filters
  CHANGELOG.md
  Cargo.toml
  bob-backend/Cargo.toml
  bob-backend/src/pearl/holder.rs
  bob/Cargo.toml
Labels: required for release

#422 420 error logging reduce
  CHANGELOG.md
  bob-backend/Cargo.toml
  bob-backend/src/core.rs
  bob-backend/src/interval_logger.rs
  bob-backend/src/lib.rs
Labels: required for release, backport to v2.0

#419 402 add grpc exists to bobp
  CHANGELOG.md
  bob-apps/bin/bobp.rs
Labels: required for release

#481 removed warning
  bob-apps/bin/bobp.rs
Labels: Skip-Changelog
